In [1]:
#Working With Numpy Library (Arrays)
# Creating a NumPy Array

import numpy as np

try:
    array = np.array([1, 2, 3, 4, 5])
    print("Array created successfully:", array)
except Exception as e:
    print("Error occurred while creating the array:", e)


Array created successfully: [1 2 3 4 5]


In [3]:
# Array of Zeros or Ones
# To create an array filled with zeros:
zeros = np.zeros((3, 3))  # A 3x3 array of zeros
ones = np.ones((2, 4))  # A 2x4 array of ones

print(zeros)
print("ones")
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Creating a Range of Numbers
# To create a sequence of numbers:
range_array = np.arange(10, 50, 5)  # From 10 to 50, step by 5
print(range_array)

[10 15 20 25 30 35 40 45]


In [5]:
# Creating a Linearly Spaced Array
# To create a series of values, evenly spaced between two bounds:
linear_spaced = np.linspace(0, 1, 5)  # 5 values from 0 to 1
print(linear_spaced)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
# Reshaping an Array
#To transmute the shape of an array, altering its dimensions:
reshaped = np.arange(9).reshape(3, 3)  # Reshape a 1D array into a 3x3 2D array
print(reshaped)
print("\n4 X4 array\n")
reshapednew = np.arange(12).reshape(3, 4)  # Reshape a 1D array into a 4x4 2D array
print(reshapednew)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

4 X4 array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# Basic Array Operations
# To perform elemental manipulations upon the arrays:
import numpy as np

try:
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    
    # Element-wise operations
    sum_array = a + b
    difference = b - a
    product = a * b
    
    print(f"sum: {sum_array}")
    print(f"difference: {difference}")
    print(f"product: {product}")

except Exception as e:
    print("An error occurred:", e)


sum: [5 7 9]
difference: [3 3 3]
product: [ 4 10 18]


In [9]:
# Matrix Multiplication
# Basic dot product Operation:

try:
    # Define the arrays
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    
    # Element-wise operations
    sum_array = a + b
    difference = b - a
    product = a * b
    
    # Print the results of element-wise operations
    print(f"Sum: {sum_array}")
    print(f"Difference: {difference}")
    print(f"Product: {product}")

    # Compute and print the dot product
    print("array a:", a.reshape(1, 3))
    print("reshaped array b:\n",b.reshape(3, 1))
    result = np.dot(a.reshape(1, 3), b.reshape(3, 1))  # Dot product of a and b
    print(f"Dot product: {result}")
    
except Exception as e:
    print("An error occurred:", e)


Sum: [5 7 9]
Difference: [3 3 3]
Product: [ 4 10 18]
array a: [[1 2 3]]
reshaped array b:
 [[4]
 [5]
 [6]]
Dot product: [[32]]


In [10]:
# Accessing Array Elements
# Accessing array elements with useful syntax:
# element = a[2]  # Retrieve the third element of array 'a'
row = reshaped[1, :]  # Retrieve the second row of 'reshaped'
#print(element)
print(row)

[3 4 5]


In [11]:
#Boolean Indexing
#To filter the elements of an array through the sieve of conditionals:
filtered = a[a > 2]  # Elements of 'a' greater than 2
print(filtered)

[3]


In [12]:
# Aggregations and Statistics
# Statistical operations on np arrays:
mean = np.mean(a)
maximum = np.max(a)
sum = np.sum(a)
print(f"mean: {mean}")
print(f"maximum: {maximum}")
print(f"sum: {sum}")

mean: 2.0
maximum: 3
sum: 6
